worker00: scrapy crawl ajio_price_data
worker01: scrapy crawl flipkart_price_data
worker02: scrapy crawl amazon_price_data
worker03: scrapy crawl nykaa_price_data
worker04: scrapy crawl pantloons_price_data
worker05: scrapy crawl puma_price_data
worker06: scrapy crawl paytmmall_price_data
worker07: scrapy crawl reliance_price_data
web: scrapyrt -p 80